# Generated by Django 4.2.4 on 2023-08-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('product_price', models.IntegerField()),
                ('product_desc', models.TextField()),
                ('product_time_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
